import streamlit as st
import pandas as pd
from sklearn import linear_model

st.write("""
# Simple Sales Prediction App

This app predicts the **sales generated by different advertising mechanisms**!
""")

st.sidebar.header('User Input Parameters')

def user_input_features():
    tv = st.sidebar.slider('TV', 0, 300, 147)
    radio = st.sidebar.slider('Radio', 0, 50, 23)
    newspaper = st.sidebar.slider('Newspaper', 0, 120, 31)
    input = {'TV': tv,
            'Radio': radio,
            'Newspaper': newspaper}
    features = pd.DataFrame(input, index=[0])
    return features

df = user_input_features()

st.subheader('User Input parameters')
st.write(df)

data = pd.read_csv('Advertising.csv')
data = data.drop(data.columns[0], axis=1)

X = data.drop('Sales', axis=1)
y = data[['Sales']]

regr = linear_model.LinearRegression()
regr.fit(X, y)

prediction = regr.predict(df)

st.subheader('Prediction')
st.write(prediction)
